version: '3.6'

networks:
  umbriel-network:
    driver: bridge

services:
  umbriel-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=sendmail-mongo
      - REDIS_URL=sendmail-redis
    depends_on:
      - sendmail-mongo
      - sendmail-redis
    networks:
      - sendmail-network
    links:
      - sendmail-mongo
      - sendmail-redis 
    container_name: sendmail-api
    command: yarn dev
    ports:
      - 3333:3333

  sendmail-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=sendmail-mongo
      - REDIS_URL=sendmail-redis
    depends_on:
      - sendmail-mongo
      - sendmail-redis
    networks:
      - sendmail-network
    links:
      - sendmail-mongo
      - sendmail-redis 
    container_name: sendmail-queue
    command: yarn queue
    
  sendmail-mongo:
    image: bitnami/mongodb:latest
    container_name: sendmail-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - sendmail-network

  sendmail-redis:
    image: bitnami/redis:latest
    container_name: sendmail-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - /tmp/redis:/bitnami/redis/data
    networks:
      - sendmail-network

